require('settings.system')
require('settings.keymap')

require('plugin.packer')
require('plugin.lualine')
require('plugin.nvim-tree')
require('plugin.barbar')
require('plugin.cursorline')
require('plugin.autopair')
require('plugin.symbol-outline')
require('plugin.treesitter')
