require('settings.system')
require('settings.keymap')

require('plugin.packer')
require('plugin.lualine')
require('plugin.nvim-tree')
require('plugin.barbar')
require('plugin.cursorline')
require('plugin.treesitter')
require('plugin.dashboard')
require('plugin.autopairs')
