require('settings.system')
require('settings.keymap')

require('plugin.packer')
require('plugin.lualine')
require('plugin.autopair')
require('plugin.treesitter')
require('plugin.lsp-cmp')
require('plugin.lsp-config')
require('plugin.lsp-mason')
