require('core.system')
require('core.keymap')
require('core.runner')

require('lazy-init')

-- require('plugin.packer-init')
-- require('plugin.lualine')
-- require('plugin.telescope')
-- require('plugin.nvim-tree')
-- require('plugin.bufferline')
-- require('plugin.cursorline')
-- require('plugin.treesitter')
-- require('plugin.dashboard')
-- require('plugin.autopairs')
-- require('plugin.formatter')
-- require('plugin.lsp')
-- require('plugin.cmp')
-- require('plugin.wilder')
-- require('plugin.nvim-lastplace')
-- require('plugin.nvim-lint')
